version: '3.8'

services:
  backend_rds:
    image: 664418977283.dkr.ecr.us-east-1.amazonaws.com/prod-rds:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend_redis:
    image: 664418977283.dkr.ecr.us-east-1.amazonaws.com/prod-redis:latest
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - ./redis_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
