name: Deploy RDS

on:
  push:
    branches:
      - main

jobs:
  deploy-rds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Deploy RDS instance using AWS CLI
        run: |
          aws rds create-db-instance \
            --db-instance-identifier watch-store-db \
            --db-instance-class db.t3.micro \
            --engine postgres \
            --master-username ${{ secrets.DB_USER }} \
            --master-user-password ${{ secrets.DB_PASSWORD }} \
            --allocated-storage 20 \
            --vpc-security-group-ids sg-123456 \
            --db-subnet-group-name rds-subnet-group \
            --publicly-accessible false

      - name: Wait for DB to be available
        run: |
          aws rds wait db-instance-available --db-instance-identifier watch-store-db

      - name: Output DB endpoint
        run: |
          aws rds describe-db-instances \
            --db-instance-identifier watch-store-db \