
name: Deploy Redis

on:
  push:
    branches:
      - main

jobs:
  deploy-redis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Deploy Redis ElastiCache cluster
        run: |
          aws elasticache create-cache-cluster \
            --cache-cluster-id watch-store-redis \
            --engine redis \
            --cache-node-type cache.t2.micro \
            --num-cache-nodes 1 \
            --vpc-security-group-ids sg-123456 \
            --cache-subnet-group-name redis-subnet-group

      - name: Wait for Redis to be available
        run: |
          aws elasticache wait cache-cluster-available --cache-cluster-id watch-store-redis

      - name: Output Redis endpoint
        run: |
          aws elasticache describe-cache-clusters \
            --cache-cluster-id watch-store-redis \
            --show-cache-node-info \
            --query "CacheClusters[0].CacheNodes[0].Endpoint.Address"
