name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 5s --health-timeout 3s --health-retries 3
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build and start Docker containers
        run: |
          docker-compose -f backend_rds/docker-compose.yml up -d

      - name: Wait for services to be ready
        run: |
          sleep 10  # Wait for Redis and PostgreSQL to start

      - name: Install dependencies
        run: |
          pip install -r backend_rds/requirements.txt

      - name: Run Django migrations
        run: |
          python manage.py migrate

      - name: Run Django tests
        run: |
          python manage.py test
